version: "3.8"
services:
  # PHP service
  app:
    build: ./docker/php/.
    container_name: app-php
    working_dir: /var/www/site
    volumes:
      - ./site:/var/www/site
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    working_dir: /var/www/site
    ports:
      - "8001:80"
    volumes:
      - ./site:/var/www/site
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # Postgres service
  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: caseDb
    ports:
      - "5432:5432"
    networks:
      - app-network

  #PGAdmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app-network
  # Redis service
  redis:
    image: redis:latest
    sysctls:
      - net.core.somaxconn=511
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
# Networks configrue
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  redis-data: